keys:
  - &MacStruble age1rae24hwrq3vnldppz92wkx2gqv6rml0vse76l52aaqra8m23pueqdyemh3
creation_rules:
  - path_regex: secrets\/[^\/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *MacStruble
