keys:
  - &MacStruble age1rae24hwrq3vnldppz92wkx2gqv6rml0vse76l52aaqra8m23pueqdyemh3
  - &roque age1s2jwgnw6cjk4pnyffplx6xcgutl975yynkd8lfplsndl87gyyq6srqrrdy
creation_rules:
  - path_regex: common/sops/secrets.yaml$
    key_groups:
      - age:
          - *MacStruble
          - *roque
  - path_regex: machines/nixos/roque/sops/secrets.yaml$
    key_groups:
      - age:
          - *MacStruble
          - *roque
