{{- if .Values.gateway.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  labels:
    app.kubernetes.io/part-of: ai
data:
  config.yaml: |
    model_list:
      {{- range $name, $m := .Values.models }}
      {{- if $m.enable }}
      - model_name: {{ $m.modelName }}
        litellm_params:
          model: openai/{{ $m.modelName }}
          api_base: http://{{ $name }}.default.svc.cluster.local:{{ $m.port }}/v1
          api_key: {{ $.Values.gateway.podApiKey }}
      {{- end }}
      {{- end }}
---
{{- end }}
